GRANT MONITOR, USAGE ON DATABASE HRCORP TO ROLE SF_FEDBEEF;
GRANT MONITOR, USAGE ON SCHEMA HRS IN DATABASE HRCORP TO ROLE SF_FEDBEEF;
GRANT SELECT, REFERENCES ON CORITY_V2_OHCASES IN SCHEMA HRCORP.HRS TO ROLE SF_FEDBEEF;


GRANT DB_FEDBEEF_DBO ROLE TO SF_FEDBEEF;